### ISSUE TITLE
Halo sir can you help me?

### ISSUE THREAD

**Issue by novepras** [Pikkuherkko/My-UniswapFrontend#1]
Hei iam new learning code just start 2 week a go , i want ask something ? i dont understand how to add REACT_APP_INFURA_URL_TESTNET inside .inv , is it right if i am do like this ? **->** REACT_APP_INFURA_URL_TESTNET='https://goerli.infura.io/v3/xxxxxxxxxxxxx' **<-** if iam wrong please tell me how to do it,

**Comment by Pikkuherkko** [comment]
yes, add .env file and url exactly like you said
